### ISSUE TITLE
error in setIndex when index is 0

### ISSUE THREAD

**Issue by victor-carvalho** [calmm-js/partial.lenses#117]
I was testing karet and when doing something like this I got an error on mapElems:
```javascript
const Todo = ({ todo }) => (
  <div>
    <span>{todo}</span>
    <button onClick={() => todo.remove()}></button>
  </div>
)

const Todos = ({ todos = U.atom([]) }) => (
  <div>
    {U.seq(todos, U.mapElems((e,i) => <Todo key={i}  todo={e} />))}
  </div>
)
```
When I try to remove the last element remaining I got an error on mapElems because setIndex returned undefined.

I can fix it by substituting U.atom([]) by U.view(L.define([]), U.atom([])).

Is setIndex intendend to return undefined in this case?

**Comment by polytypic** [comment]
Yes, this behaviour, namely that removal of the last element of an array triggers removal of the array itself, is by design as mentioned in the documentation of [`L.index`](https://github.com/calmm-js/partial.lenses/#L-index).  Partial lenses are designed to support "propagating removal".  [For example](https://calmm-js.github.io/partial.lenses/playground.html#DIOgTgpgtg9gbhAFAbQAwBoAEHtdQXS2WOQEZ8L8BKIA):

```js
L.remove([0, 0, 0, 0], [[[[1]]]])
// undefined
```

Operations on both objects and array like objects behave similarly.  [For example](https://calmm-js.github.io/partial.lenses/playground.html#DIOgTgpgtg9gbhAFAbQAwBoAEAiAHtrVAXS2QG9cAuTZARiIF8iBKIA):

```js
L.remove([0, "x", 0], [{x: [1]}])
// undefined
```

In cases where certain objects or array like objects must not be removed, one needs to explicitly make it so by using e.g. `L.define([])`.  [For example](https://calmm-js.github.io/partial.lenses/playground.html#DIOgTgpgtg9gbhAFAbQAwBoAEHOgCYQBmAlgHZLIC6AlFjqpVss8gIyUc1A):

```js
L.remove([0, 0, L.define([]), 0, 0], [[[[1]]]])
// [[[]]]
```

[And also](https://calmm-js.github.io/partial.lenses/playground.html#DIOgTgpgtg9gbhAFAbQAwBoAEoAmEBmAlgHZIDeAvgJRYBEAHrVqgLpbJn0BcmyAjCwosqQA):

```js
L.remove([0, L.define({}), "x", 0], [{x: [1]}])
// [{}]
```

Conversely, partial lenses also support "optimistic queries and updates".  [For example](https://calmm-js.github.io/partial.lenses/playground.html#DIOg5gpgLgFA2gBgDQAIBEAPNqEF1UCuAdgCYQBmAlkRCQJRA):

```js
L.get([0, "x", 0], undefined)
// undefined (no errors)
```

[And also](https://calmm-js.github.io/partial.lenses/playground.html#DIOgzgpgLgFA2gBgDQAIBEAPNqEF1UCMqArgHYAmEAZgJakTkCUQA):

```js
L.set([0, "x", 0], 1, undefined)
// [{x: [1]}]
```

Note that there is also a [Gitter channel](https://gitter.im/calmm-js/chat) for discussing lenses (and other libraries in the Calmm org).

**Comment by victor-carvalho** [comment]
Thanks for the info!
Great work in this library, I was looking for something like this for my project.

**Comment by polytypic** [comment]
No problem. :)

Feel free to ask questions here or in the Gitter channel whenever something is unclear.
