### ISSUE TITLE
Modifying a nested data structure?

### ISSUE THREAD

**Issue by skokenes** [calmm-js/partial.lenses#216]
This isn't an issue but really a question about if/how partial.lenses could be used to solve a data transformation that I am working on.

I have a nested data structure that I am working on that should be 3 levels deep; let's call the levels "rows", "columns", and "cells" like a table. So I might have a structure like:

```javascript
[
    {
       value: "a",
       nodes: [
           {
               value: "b",
               nodes: [
                   {
                       value: "c",
                       nodes: []
                   },
                   // ...etc
               ]
           },
           // ...etc
        ]
    },
    // ...etc
]
```

Sometimes however, the rows or columns levels might be missing. So I may just get back a single level or two levels. In those scenarios, I want to fill the gaps in tree with a default value. So lets say that I received the following data structure:
```javascript
[
    {
       value: "c",
       nodes: []
    },
    // ...etc
]
```

I want to turn that into something like:
```javascript
[
    {
       value: "DEFAULT_ROWS_VALUE",
       nodes: [
           {
               value: "DEFAULT_COLUMNS_VALUE",
               nodes: [
                   {
                       value: "c",
                       nodes: []
                   },
                   // ...etc
               ]
           }
        ]
    }
]
```

Is this kind of transformation possible with this lib? I've struggled to figure out how I could dynamically accomplish this. I do have flags that let me know if columns and rows are present in the returned data or not. Thanks for any advice

**Comment by polytypic** [comment]
Hi, on quick glance this seems like something that should be possible. I am busy today, but might have time to draft an example tomorrow. Is the goal just to transform (augment) the data structure (one way or two way) or to treat it as if it were augmented and then do something with the data structure (modify it or query something from it)?

**Comment by skokenes** [comment]
The goal is to transform it for reading by a charting library. I did get something working for this but had to essentially create 3 lenses, 1 for each scenario. Then I pick which one to use based on whether there are rows, columns, or both. I don't have that code with me but can post it here later today. Would love your feedback on it, thank you for looking at this!

**Comment by skokenes** [comment]
Here's what I have currently, where `dataLens` is the final lens that will be used. Is there a better way to accomplish or approach this?
```javascript
const recurseLens = L.lazy(rec =>
  L.ifElse(
    d => d instanceof Array,
    L.collect([L.elems, rec]),
    L.pick({
      value: ["value", L.valueOr("")],
      nodes: ["nodes", rec]
    })
  )
);


let dataLens = [];
if (hasRows === false && hasColumns === false) {
  // insert row and column, then recurse
  dataLens = [
    L.collect(
      L.pick({
        value: ["value", L.define("DEFAULT_ROW")],
        nodes: L.collect(
          L.pick({
            value: ["value", L.define("DEFAULT_COLUMN")],
            nodes: recurseLens
          })
        )
      })
    )
  ];
} else if (hasRows === false) {
  // insert row, then recurse
  dataLens = [
    L.collect(
      L.pick({
        value: ["value", L.define("DEFAULT_ROW")],
        nodes: recurseLens
      })
    )
  ];
} else if (hasColumns === false) {
  // Get the rows, then insert columns, then recurse
  dataLens = [
    L.collect([
      L.elems,
      L.pick({
        value: ["value", L.valueOr("")],
        nodes: L.collect(
          L.pick({
            value: ["value", L.define("DEFAULT_COLUMN")],
            nodes: ["nodes", recurseLens]
          })
        )
      })
    ])
  ];
}
else {
    // If rows and columns exist, just recurse the whole structure
    dataLens = recurseLens;
}
```

**Comment by polytypic** [comment]
Is there a way to tell whether two level deep structure has rows or columns based on just the structure itself (and not by using variables external to the data structure like in the example)?

**Comment by polytypic** [comment]
The `recurseLens`

```js
const recurseLens = L.lazy(rec =>
  L.ifElse(
    d => d instanceof Array,
    L.collect([L.elems, rec]),
    L.pick({
      value: ["value", L.valueOr("")],
      nodes: ["nodes", rec]
    })
  )
)
```

filters a nested structure so that only `value` and `nodes` properties are left.  Is that necessary?  IOW, does the input data contain additional properties that need to be dropped, for example?

Also, the `recurseLens` handles arbitrarily deep nesting.  Is that also intentional or is the maximum depth always 3 (something like rows, columns, and data nodes)?

I assumed that neither of the above aspects is actually necessary.  Here is [a playground that does a kind of augmentation](https://calmm-js.github.io/partial.lenses/playground.html#PTAEBUCcE9QOwKYHMCGAXAlnJo0AsFQBjAezgDMMkAoUuAZzWLMpwF5QBvPFegJRIB3egC5Q5FABt6CADSge9AMIlJAVwC2DMROkIAvtWogIBGaABWaxqABGajJIAmuBDafoUd3ghdlmFFS0ZDYoTk4AMggAbgiSoBzRUmqEbAB88CRObgkZANqcSepymdn0+gC6wQxMHmheHACSAHQyAI4AFNR5FbLUYZExcR0A5HBZCCMAlH10rM2KKupa9KAA-KADUbGSo6TLcNOgYnzNGNlwmGjQsyxUC7wCwuub4dvDI5BCRydnF1fQahTIwmcBmQh0RiQNRENCrEgAB0wRFW5BIkFeTiwOBQcCcwHRuEguPoaMgGmxoCw9HOhC8kiGkmqNmptPekkaCSp9BIuVAEWaKARCMk0AAgmgOnkBXEEBp6PIxhN6CNetySMDIUwtozOYlkqkMhgeXy8tQBRohQjsR1xmVTXa3PICkUUvJHeUKhUZtRWdl2Y0OsaNdQqsYwGDjQEoTC4Zs4Js1EgNAhLpTEcjmdqkynLlyOtxHkIFQpeEtNAx9FM+S12l0en1FqoK6sNn6EAHjpiA6NshI1JImPsK9NG0Xnm2GGzdV2dTtAyM+ygB0wvoJpkCjJISEgOvzmkgEJLl8nU5K5lQZqA6ihq8DqNvd9fPKApkA).  If I understood the problem correctly, then the key is that when the input does not contain columns, then the default column needs to be inserted inside every row.  The code in the playground achieves this using the `insideLevelI` isomorphism constructor.

**Comment by skokenes** [comment]
The data structure itself does not tell me whether rows or columns are included.

It's not necessary to filter the additional properties off. I don't show it in the example code, but I actually rename the properties as well in my real implementation. The reason I do this is to try and keep the data provider somewhat agnostic from my charting library; otherwise if I switch to a different data provider, I will have to update my charting library to accept a new format. Does this step have negative performance implications?

The data can be arbitrarily nested after the rows and columns, so that was on purpose. Sorry, I should have mentioned that.

Thanks for coming up with an example solution, I'm working through it now. What is the global `I` that you are using in `I.seq()` for example?

**Comment by polytypic** [comment]
The `I.seq` function comes from the [Infestines](https://github.com/calmm-js/infestines) library.  It just pipes a given value through given unary functions.  IOW, `I.seq(x, f_1, ..., f_N)` is equivalent to `f_N(...f_1(x)...)`.

**Comment by polytypic** [comment]
BTW, one thing that is important to understand about optics is that the [API is different](https://calmm-js.github.io/documentation/mental-optics/#/12) (press `s` and go forward from that slide) compared to a traditional map/filter/reduce library.  In particular, *operations* are separated from optics.  An optic roughly specifies how the elements are selected from a data structure and the operation specifies what to do with those elements.  So, when using the library, one first constructs an optic using primitive optics and optic combinators and then passes that optic and a data structure to an operation to get a result.

```js
operation( optic , data ) ~> result
```

When you look at `recurseLens`

```js
const recurseLens = L.lazy(rec =>
  L.ifElse(
    d => d instanceof Array,
    L.collect([L.elems, rec]),
    L.pick({
      value: ["value", L.valueOr("")],
      nodes: ["nodes", rec]
    })
  )
)
```

one thing that pops out is `L.collect`, which is an operation rather than an optic combinator.  When you apply an operation to an optic you get a function from data to a result rather than an optic.  IOW, you get an ordinary unidirectional function.  Of course, such ordinary functions are fine as read only optics, but usually one rather wants to create bidirectional optics.  In this case, instead of using `L.collect` one could use `L.partsOf` to create a bidirectional lens like [this](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBAhgEwQGQKYDdUBsYF4bpxYCuqeAfDGCAqhBTANoDehJqANFTXV6gB5QATnABcMAOQAHISCmohUAJ4SAvgF0AUKEiwEcKHDwwAkgDoIqAI4AKTY3UdNiFBmw2J1WhICUTl2iYWB6gJAC2YL7+SIHuErIA7r6aPpra4NAwQqjAxEKWaJDGyGZYcABeSjbZwAwlAJYAZgCiWJZ2AIJCIkpm9RBdPU4lUnCKEADyjTYl2KhhEFw1fjAA9KswADwAtDAAciCwAAYloVg5UEeaI-XAANY2zJoAah3IAKrN4owARGykPy4JX+qAmQhsPx+Pkcmi8dG+PzhEEBWRyWlUqR8qU06xgAHUyMA4GAYABzVCwOD0ABGqEaIGyok0WBApJsMBK5Kg1RyeQKqEgXH0hh8MGxuI6YAQ3ASMAShOJ8DaIBgligTJZbI5FgpNkYNT5qEKi215zgjRNJQSAAsBTYbAB9Lh3VBKUW4SgupR4XD4H6vD7NKGOGA-CAgMJkKDW+pgFHCuCinxAA).

**Comment by skokenes** [comment]
Thanks, this helps a lot. Especially thinking of an optic as a "selector" and separating it from the operations. There are probably a few places in my code where I'm using `L.collect` in some weird/unnecessary ways, mainly to handle dealing with traversing arrays

**Comment by skokenes** [comment]
I'm struggling a bit with taking your original solution and modifying it. If I copy and paste as is, its great. But there are two modifications that I'm trying to make:

- incorporate L.pick or some other optic to tweak the data format like you showed in the second example
- incorporate recursion after the first 2 levels have been cleared

I'm pretty lost on where I would incorporate those changes

**Comment by polytypic** [comment]
Something like [this](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBKYDMCWBzGBeGBvAFgQwgCUQB3CALhigCcBXAUwBoZ8IBhEAG1oFtJKaDAL4AoEfGgw8AE2kAZegDd6nDDEV5u9DAD4YYENPoRdMANpYNW5gaMQhAXXHhJ0vFDxqAkgDoI9AEcAChEzB0YRGXklFSCAcjw4gEoIqIVlTniAI2TU2XTYuOBc50RUH1YObj4TAH4pfJjMoq5eMGSYSkIfJCMwKCQoAE8I+GQUCoJiMhh6tKb46lIOrp6+geGRJLEAeh2YDjBlaigTTwgkMBRObVttKBAqHHu8ahR6WAQQah53KTBpE96GA4OABmAGCYSIMcCI9jAAAaXMD0agFThyBEwG6QKiPeDHWBQZ5SajUPBDGAgBAwZGo-SGYw+UqSAmoqAAOUZcjUdLRTR56D0ch8AAckMAANZBLAiABqAEE5ABVACilDMACIrAxNcwRTr6AB5ahBTWapLhGDwgA8AFoYAAVEkIxUq1VYxQmBGGrFIEwAK1okgeMGkjwgIB42jZ1Au4BEdwo5k1Sb1tLAKP5GTkTiE2zh+0OhLOINe5Mp1IZdjxQKor3en2+v1geABQJB8HBkJg0OJhcRfPRmOxwJModjrbJFJMVb51aZLNgk+HvMzqNXQpgItFr1ORoQQRFKnoPAgzEnXKMciCQ4FSQL8IVsjO+noJFHGV7MJgKCQyhBIwEDwWhOFgH1NAYLE20BYlgVBfpLh7PtYXhJF12zFQRxxcd8XAQlSQrWcaXnJNmQkVtGhzNRDVMO9qK3MwRBFX5RXFK4giTUwzCTZgLENGxGXsBwHBSUpCWHW8MOHbYnAHQ5oDoYBTikUdcVDKJ-mkHZvgQgiUWgehAXLGcFwgciXFbWgUGjfpBRgGVWGmc8WAIKo2nsJJTF8fxggHZ1tGgPdLjQUUQEuWB-VUnCnj+ah6GAWg43-FRKUnEwDKgIzCNMqsyOYnxODwAAvIYghXe8InhR1HjgmAgpOEKYDCiLmvi0VgWMtTcJgegYXpScqRRGAeG+bQbi-XSHgHTTPBRD8JpUGAvmoUFqlxGCOwQ7t7ni9wmr5ExFs4KEYQHOqYoopSsuMrIQGUZlKlaGpZj09lV0oeYc3iICQLAta2hKeEAGUkB4JAiuoThKVFdrOuisdaz6uDVsG8BtFG+LPyWqbHlmt8SAHY7lt0pYZk2uDOzBJDdvofargzLNsZO79iTrHCByu2hlOyvA7oekQnNIOo3pOD6Gmib64l+0DYDJ5ItjEEVGyCECbOBKAbzGVAUjDdw8CSIA).

[Here](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBKYDMCWBzGBeGBvAFgQwgCUQB3CALhigCcBXAUwBoZ8IBhEAG1oFtJKaDAL4AoEfGhxq9PFHoAZegDd6nDDCV5u9DAD4YYEABN6EPTADaWTduaGTEIQF1x4SUdl51ASQB0EegBHAAoRCydGcWlZBWVVYIByPASASkjgaLlFFU5EgCNU9MzYnMTgQtdEVF9WDm4+MwB+KRksuNyE0HqwVJhKQl8kEzAoJCgAT3TwZBQagmIyGGaM1pL4hOpSXv7B4dGJkRSxCVhkAA91BHML9H0EYJu7pDPghBSHlPezo8rJeBVqFAAHLGHSYf70QHeMBgSHZVTmYLWLQMOygxwpRFYEQANQAgvIAKoAUUoNgYMAAPpSYAAiWmReymSgQqEwuHtYJMiBHIQ-E5wcAAqDwtTgoWQqDQ2HUUXmAY8PAAB2CrOBoNVErZMtFn2OblgeCMRjlmHJYP0aulHJy5m55isuIJJLJKKYIm5LK1Is5VvZsva725vJcv0NtBQPHoI3USNYCwgzFqXF4kD55j8ARCInOmrAwt1kWT3SagvzkrllCNJs5CRMCDwtE4sC6qYq8dIpbVlZg1dFiXrjebME2JFShzEjcj0ageZm7w8UDwKSAA) is a similarly structured solution using only ordinary functions.

It sounds like in this case you need to perform a whole data structure transformation only in one direction.  Without knowing more, I probably wouldn't recommend using optics in this particular case.

**Comment by skokenes** [comment]
Thanks for your help on this, I'm learning a lot.

It is transformation in one direction; I started using partial.lenses for it because I like a lot of the functions it provides for traversing the data and dealing with missing values (L.lazy, L.valueOr, etc).

What alternatives would you recommend to solving this problem that don't involve optics? Just writing the transformation out with `map`, `reduce`? Or are there alternative "helper" functions that you would turn to in data transformations like these?

**Comment by skokenes** [comment]
Thanks for taking the time to put these together, they are really helping me learn.

I see what you are saying about not leveraging optics if just doing a transformation in one direction, which is the case here for sure. I do leverage optics for bidirectional things in several places in my application, but I think I then got used to using `L` and started reaching for it in places where it wasn't necessary. Probably a good opportunity for me to clean up some code. Thanks again for the feedback
