### ISSUE TITLE
L.defaults should replace null and undefined values

### ISSUE THREAD

**Issue by Hilzu** [calmm-js/partial.lenses#24]
`L.defaults` is a simple alias for `L.replace(undefined, x)`. I would expect it to replace `null` values in addition to `undefined`. Usually I want to handle both values as "value missing". Handling both gets a bit involved with the current functions.

```javascript
> L.get(P("a", L.defaults(0)), {})
0
> L.get(P("a", L.defaults(0)), { a: 3 })
3
> L.get(P("a", L.defaults(0)), { a: undefined })
0
> L.get(P("a", L.defaults(0)), { a: null }) // I would expect this to be 0
null 
> L.get(P("a", L.defaults(0)), undefined)
0
> L.get(P("a", L.defaults(0)), null)
0
// Handling undefined and null
> L.get(P("a", L.replace(null, 0), L.replace(undefined, 0)), { a: null })
0
> L.get(P("a", L.replace(null, 0), L.replace(undefined, 0)), { a: undefined })
0
```
There should be a way to do this more easily.

**Comment by polytypic** [comment]
First I'd like to just note that, strictly speaking, the third and last examples with `{ a: undefined }`

```js
> L.get(P("a", L.defaults(0)), { a: undefined })
0
> L.get(P("a", L.replace(null, 0), L.replace(undefined, 0)), { a: undefined })
0
```

are outside of the domain of partial lenses due to the property whose value is `undefined` (which is not valid JSON) which might interact with the special treatment of `undefined` in unexpected ways.

The main reason that `null` is not treated the same as `undefined` by default is that `null` is a perfectly valid JSON value while `undefined` is not.  By not treating `null` (or the empty string `""` or `0` or `false`) as a special value, partial lenses *can* be used to manipulate arbitrary JSON and to implement the desired application specific semantics to deal with `null` (and other JSON values).

In some applications you may indeed want to treat `null` roughly the same as `undefined` (IOW, "doesn't exist" or "remove from the data structure").  In other applications `null` may need to have completely different meaning.  In the project during which I started working on partial lenses, at least one of the APIs we used had special meaning attached to `null`.  Having a `null` there meant that some property was to be explicitly removed from the underlying DB and if the property was merely removed from JSON it meant that part was not to be changed (when updating data with a PUT request).  So, there was a very clear need to differentiate between `undefined` (meaning that something didn't exist or was to be ignored) and `null` (meaning that the user requested to explicitly remove something).

In general, I think that for use cases like this, namely treating e.g. `null` as "value missing", it would be best to write new combinators to achieve the desired behaviour for reading *and* writing through the lens.  Note the following:

```js
> L.get(P("a", L.replace(null, 0), L.replace(undefined, 0)), { a: null })
0
> L.set(P("a", L.replace(null, 0), L.replace(undefined, 0)), 0, { a: null })
undefined
> L.set(P("a", L.replace(null, 0), L.replace(undefined, 0)), null, { a: null })
{ a: null }
> L.set(P("a", L.replace(null, 0), L.replace(undefined, 0)), undefined, { a: null })
undefined
```

The above behaviour for `L.set` operations (and the last one is equivalent to `L.remove`) might or might not be what is desired.  If the behaviour is desired, then you could just write a combinator like this:

```js
const myDefaults = v => P(L.replace(null, v), L.replace(undefined, v))
```

and use it:

```js
> L.get(P("a", myDefaults(0)), { a: null })
0
> L.set(P("a", myDefaults(0)), 0, { a: null })
undefined
> L.set(P("a", myDefaults(0)), null, { a: null })
{ a: null }
> L.set(P("a", myDefaults(0)), undefined, { a: null })
undefined
```

However, I suspect that, if not in this case, then in other similar cases you might want different behaviour when writing through the lens.  Perhaps some sort of type based filtering/default?

I'd like to better understand this use case to be able to recommend an approach that works.  What is the schema or schema(s) of the JSON (property) being manipulated?

**Comment by Hilzu** [comment]
The `{ a: undefined }` was meant to show that the object has no such field. I forgot that objects can have keys whose value is `undefined`. partial.lenses work the same way in those two cases if the key exists or not.

That set behaviour is not what I want. `defaults` seems to work in a surprising way in the set cases. With this example I would expect to get an object with the `a` key set to 0:

```javascript
> L.set(P("a", L.defaults(0)), 0, {})
undefined
```

I think that  behaviour supports the case for `defaults` being something else that just an alias for `replace`.

The JSON is created by reading from a MySQL database, where the absence of a value is marked by NULL. That NULL is directly transformed to `null` in the JSON by the node MySQL driver. There is no other transformations done to the JSON before it reaches the browser where it's used with partial.lenses.

**Comment by polytypic** [comment]
Hmm...  Just a quick note.  One reason that `L.defaults` works the way it does is that it allows removal to propagate.  Consider the tutorial example:

```js
const textIn = language =>
  L.compose(L.prop("contents"),
            L.required([]),
            L.normalize(R.sortBy(R.prop("language"))),
            L.find(R.whereEq({language})),
            L.defaults({language}),
            L.prop("text"),
            L.defaults(""))
```

Consider the part `L.defaults({language})`, in particular, which is equivalent to `L.replace(undefined, {language})` and performs replacement both forwards and backwards.  This means that when removing the `text` property through the lens the removal propagates as a mere `{language}` object will be replaced to `undefined`.

I think that a combinator that behaves like `L.defaults` is very useful for allowing one to make lenses with propagating removal behaviour.  However, perhaps the name `L.defaults` is not ideal and there should perhaps be another default value providing combinator for use cases such as yours.

The second use of `L.defaults` in the example, namely `L.defaults("")`, is perhaps closer to your use case.  In the cases where I've used that pattern (the example is based on actual use cases), having a text with an empty string is pretty much equivalent to having no text at all, so it makes sense to just remove such a text from the model.  But I can see there may be use cases where you'd want removal to be more explicit such that writing the default value doesn't remove the property.

I'll have to think about this more.

**Comment by polytypic** [comment]
Does the `L.valueOr` combinator introduced in PR #26 seem like it would work in your use case?

(Re)Naming suggestions for `L.defaults` and `L.valueOr` are welcome.

**Comment by polytypic** [comment]
BTW, one could read `defaults` as provides "default structure".

**Comment by Hilzu** [comment]
valueOr seems to be what I want.

I'm not awfully familiar with the semantics of removing values with lenses as I haven't really needed that yet.

`""` and `null` really can't be handled the same in my use case. When the value binded to an input element in React, `null` and `undefined` mean that the input is uncontrolled. Switching the element from controlled to uncontrolled creates a warning.

**Comment by polytypic** [comment]
I'll shortly publish a new version with the `valueOr` combinator added.
